README.md
balance.go
balance_test.go
client.go
error.go
hlr.go
hlr_test.go
lookup.go
lookup_test.go
main_test.go
message.go
message_test.go
otp_message.go
otp_message_test.go
recipient.go
voice_message.go
voice_message_test.go

Nothing important, just few issues that gometalinter reports.
1. Fixing declarations according to golint complains.
2. Renamed Id to ID according to Go standard.
3. Added godocs to exported structs.
4. Fixed formatted messages.
5. Added goreportcard.

Fixing linter warnings

---

client.go
hlr.go
hlr_test.go
lookup.go
lookup_test.go
message.go
message_test.go
verify.go
verify_test.go
voice_message.go
voice_message_test.go

Only use JSON data when sending POST requests to the MessageBird API.

Switch from url encoded data to JSON data

---

message.go

When generating request data for a message, do not attempt to format the message param's ScheduledDateTime from message if it hasn't been set.

Only format ScheduledDateTime if it has been set when generating message request data

---

client.go

This paves the way for support for the Voice API which uses DELETE and PUT.

Explicitly set the request method instead of inferring it

---

message.go

The datacoding used in SMS message is always 'plain' after I tried different values for DataCoding.
It looks like the json name for datacoding attribute is 'datacoding' rather than 'dataCoding'.

Fix 'datacoding' attribute error

---

.travis.yml

- Also added an explicit requirement for Go stable.
- The Go master is allowed to fail, so it does not break the build in
case of a broken version.

Bump minimum required Go version to 1.8

---

client.go
voice/call.go
voice/call_test.go
voice/callflow.go
voice/callflow_test.go
voice/leg.go
voice/main_test.go
voice/paginator_test.go
voice/recording.go
voice/recording_test.go
voice/transcription.go
voice/transcription_test.go
voice/voice.go
voice/webhook.go
voice/webhook_test.go

This changeset introduces (optional) integration tests for the Voice API.
The approach uses a test key that can be set with the `MB_KEY_TEST` env var.

Various voice fixes and integration tests

---

client.go

there was a tiny booboo a couple of years ago. I'm fixing it now: 
Actually use the logger we have on the client to log.

actually use the logger passed on the client constructor

---

client.go

Hi! Go’s http package doesn’t specify request timeouts by default, but it's always good to specify one.

Set Timeout for http.Client

---

balance.go
balance_test.go
client.go
error.go
error_test.go
hlr.go
hlr_test.go
main_test.go
message.go
message_test.go
mms_message.go
mms_message_test.go
verify.go
voice/main_test.go
voice_message.go

Should the tests for `New` factory be duplicated? As the tests now runnig under `NewV2` factory.
https://github.com/messagebird/go-rest-api/issues/34

Deprecate ErrResponse error with ErrorResponse instance

---

client.go

Hi,
I am currently completing the programming assignment for the go job but was having no luck with calling the Lookup method. 
The only error I was getting back from the package was 
"2018/07/07 13:51:57 invalid character 'M' looking for beginning of value"
This turned out to be caused by the package doing a POST when the API wants a GET.
Thanks,

Fixed failing calls to Lookup

---

recipient.go

Most of the phone numbers (11 numbers) would throw an error during unmarshaling the response from the REST API, due to `int` would be only 32-bits long on i386 and 32-bits int is < 2,147,483,647 (10 numbers). This small fix would remove this inconvenience

Fix unmarshal error for recipient on i386

---

README.md
UPGRADING.md

Adds a upgrade guide that documents breaking changes when upgrading to V5.
Closes #39

Upgrade guide

---

lookup/lookup.go
lookup/lookup_test.go

Lookup uses GET, not POST - see [docs](https://developers.messagebird.com/docs/lookup#request-a-lookup).

Fix error: lookup uses GET

---

voice/callflow.go
voice/callflow_test.go
voice/recording.go
voice/transcription.go

Added field "Transcribe" to CallFlowRecordStep object. 
Fixed values for MaxLength and Timeout in CallFlowRecordStep object.
Fixed Transcriptions in recordings.
Replace field "error" with field "status" in Transcription object.

Fixes for transcriptions

---

voice/callflow.go

Implemented `onFinish` attribute for `step[].options` (https://developers.messagebird.com/docs/voice-calling#call-flows) as
```go
CallFlowRecordStep struct{
// ...
OnFinish string
}
```
This is required for chaining call flows while staying on the same callID/legID. A specific example would be how `onFinish` is used here: https://github.com/messagebirdguides/automated-surveys

implemented onFinish attribute for CallFlowRecordStep

---

conversation/conversation.go
conversation/conversation_test.go
conversation/testdata/allConversationListObject.json

It's require to define limit and offset to list conversations. This pull request allow to list conversations without passing this options (list all).
It also avoid the sdk to crash(panic) in case options is set to nil.

improvement(conversation) allow pass option as nil to list all

---

conversation/api.go
conversation/conversation.go
conversation/message_test.go
conversation/testdata/allMessageListObject.json
conversation/testdata/allWebhookListObject.json
conversation/testdata/messageListObject.json
conversation/webhook_test.go

It's require to define limit and offset to list conversation messages. This pull request allow to list conversation messages without passing this options (list all).
It also avoid the sdk to crash(panic) in case options is set to nil.

improvement(conversations lists) allow pass option as nil to list all

---

error.go
error_test.go

It turns out most clients rely on the built-in error interface, and
don't explicitly cast to ErrorResponse. Those clients would only see
a very generic "The MessageBird API is currently unavailable" message.
After this change, Error() will return a concatenated list of the
actual error descriptions returned by the MessageBird APIs. If desired,
clients can still cast to ErrorReponse to inspect the "code" and "param"
fields for the individual API errors

Improve ErrorResponse's Error() implementation to be more specific.

---

sms/message.go
sms/message_test.go

This PR adds support for the `shortenUrls` URL parameter that is available to limited customers when sending out a message.

Add support for the shortenUrls parameter in message

---

.github/workflows/tests.yml
balance/balance_test.go
contact/contact_test.go
conversation/conversation_test.go
conversation/hsm_test.go
conversation/message_test.go
conversation/webhook_test.go
error_test.go
go.mod
go.sum
group/group_test.go
hlr/hlr_test.go
internal/mbtest/helper.go
lookup/lookup_test.go
mms/message_test.go
number/number_test.go
signature/signature_test.go
sms/message_test.go
verify/verify_test.go
voice/call_test.go
voice/callflow_test.go
voice/paginator_test.go
voice/recording_test.go
voice/transcription_test.go
voice/voice_test.go
voice/webhook_test.go
voicemessage/voice_message_test.go

This PR introduces the usage of [testify](https://github.com/stretchr/testify) for testing this package.
This is a known and popular testing suite for Go.
It makes the tests very easy to maintain and concise.  All assertions have been simplified.  The next steps (in another PR) are to mock the responses with testify. 
——
This PR could ideally be merged after the move to Github Action cf. https://github.com/messagebird/go-rest-api/pull/96
  —-
Cc @rfeiner @CoolGoose

Use testify for testing.

---

voice/call_test.go
voice/callflow.go
voice/callflow_test.go

This field is deprecated now although users still can send and receive it.

Deprecate CallFlow Title usage

---

README.md
client.go
conversation/api.go

Whatsapp sandbox is now available as a channel in conversations so we don't need a separate endpoint for it anymore

Remove the feature flag for whatsapp sandbox
